# This analysis the output from an alterntive version of the model in which each fork has an additional parameter "ori" which is the position of the origin from which it initiated (cerevisiaeChrII_15FF_mapOri.bc)
# This finds the mean replicon length for each origin
# The results are saved in dataframes (which can later be plotted)
# It does not include running the Beacon Calculus (bcs) script

################################################################################
import pandas as pd
import numpy as np
import os
import math
import datetime
import time
#------------------ 01 SETUP ------------------
start_time = time.time() # for tracking how long the script takes to run

bcsOutputName = '15FF0p05d_fitted_mapOri_s500_chrII'# 500 simulations of a fitted model for chromosome II with F=15 and recycling rates of 0.05, with additional "ori" parameter
# (fitted script not provided, must be generated by running fitting_mapOris_chrII.py)
label = '15FF0p05d_chrII'  # to identify which version of the model is being used
todaysDate = datetime.date.today().strftime("%d%m%Y")

# getting the positions of origins
inputFilePath = "data/origin_positions.csv" # contains the position ('i') and chromosome number ('ch') of each origin
ori_df = pd.read_csv(inputFilePath,header=0)
chrII_ori_df = ori_df[ori_df['ch']==2].reset_index(drop=True) # getting the origins just on chromosome II
chrII_ori_df = chrII_ori_df.assign(emptyColumn=0) # adds a column where every value is zero (Automatically named "emptyColumn" )

# seting up a dictionary mapping each origin to a count of the number of times DNA is replicated by forks initiating from that origin (over all simulations)
ori2replicons = dict(zip(chrII_ori_df['i'], chrII_ori_df['emptyColumn']))


#------------------ 04 OUTPUT_ANALYSIS ------------------
bcsOutputPath = f"bcs_output/{bcsOutputName}.simulation.bcs"
with open(bcsOutputPath, 'r') as file:
    bcs_output = file.read()

iterations = bcs_output.split(">")[1:]   # splitting it into seperate simulations (iterations)
numberOfIterations = len(iterations)
for index, iteration in enumerate(iterations):  # iterating over each simulation
    alreadyDone = []
    
    for line in iteration.splitlines(): # iterating through each line of the simulation output
        splitLine = line.split('\t')
        if len(splitLine) == 7 and splitLine[2] in ["FL","FR"]:  # lines where DNA is replicated
            repPos= int(splitLine[4]) # position being replicated
            ori = int(splitLine[6]) # identifying the origin which the replication fork initiated from
            if repPos not in alreadyDone: # prevents replication of the same position being accounted for multiple times within the same simulation
                alreadyDone.append(repPos)
                ori2replicons[ori]+=1 # countig the number of positions replicated by forks from that origin             

# Creating a datareame containing the mean replicon length of each origin


for ori, replicon in ori2replicons.items():
    ori2replicons[ori]= replicon/numberOfIterations # finding the mean replicon length  
replicons_df  = pd.DataFrame(list(ori2replicons.items()), columns = ['i','replicons']) # making the dataframe


#------------------ 03.0 SAVING_RESULTS ------------------

# making a new folder to store the output
new_folder = f"{todaysDate}_replicons_{label}"
folderPath = f'output/{new_folder}'
os.makedirs(folderPath, exist_ok=True)

# saving dataframes
replicons_df.to_csv(f"{folderPath}/fullReplicon_{label}.csv", index=False)

# calculating how long the script took to run
end_time = time.time()
duration = end_time - start_time
duration/=60 # converting from seconds to minutes
print(f"The script took {duration} minutes to run.")

print("Finished")
